teams:
  - name: iguazu-maintainers
    maintainers:
      - on-waterfall
    members:
      - dimrogovoy
      - VladimirMezin
  - name: lfdt-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
repositories:
  - name: .github
    teams:
      iguazu-maintainers: maintain
      lfdt-staff: maintain
    visibility: public
  - name: governance
    teams:
      iguazu-maintainers: maintain
      lfdt-staff: maintain
    visibility: public
  - name: waterfall-docs
    teams:
      iguazu-maintainers: maintain
      lfdt-staff: maintain
    visibility: public
  - name: waterfall-one-click-setup-app
    teams:
      iguazu-maintainers: maintain
      lfdt-staff: maintain
    visibility: public
